# Generated by Django 4.1 on 2022-09-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratsiyamodel',
            name='rcode',
            field=models.SmallIntegerField(default=0),
        ),
    ]
