# Generated by Django 4.1.3 on 2022-11-22 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_ratsiyamodel_rcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='ratsiyaModel',
            new_name='RatsiyaModel',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='tadbirModel',
            new_name='TadbirModel',
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('TadbirModel', 'RatsiyaModel')},
        ),
    ]
